// Sort Actions
export const SET_COHORT_SORT_FILTER = "COHORT_SORT_FILTER"
export const SET_STUDENT_CARD_SORT_FILTER = "STUDENT_CARD_SORT_FILTER"
export const SET_STUDENT_LIST_SORT_FILTER = "STUDENT_LIST_SORT_FILTER"
export const SET_COHORT_SORT_DIRECTION = "SET_COHORT_SORT_DIRECTION"
export const SET_STUDENT_CARD_SORT_DIRECTION = "SET_STUDENT_CARD_SORT_DIRECTION"
export const SET_STUDENT_LIST_SORT_DIRECTION = "SET_STUDENT_LIST_SORT_DIRECTION"

// Hide Actions
export const SET_COHORT_HIDE_FILTER = "COHORT_HIDE_FILTER"
export const SET_STUDENT_CARD_HIDE_FILTER = "STUDENT_CARD_HIDE_FILTER"
export const SET_STUDENT_LIST_HIDE_FILTER = "STUDENT_LIST_HIDE_FILTER"

// Update Actions 
// (we will make this such that it does one giant API pull/refresh from DB)
export const UPDATE_COHORTS = "UPDATE_COHORTS"
export const UPDATE_STUDENT = "UPDATE_STUDENT"
export const ADD_STUDENT = "ADD_STUDENT"
export const ADD_COHORT = "ADD_COHORT"

// User Actions
export const UPDATE_USER = "UPDATE_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"

// Touchpoint Actions
export const ADD_TOUCHPOINT = "ADD_TOUCHPOINT"

// Commit Actions
export const UPDATE_COMMITS = "UPDATE_COMMITS"